数组创建 Tensor

In [1]:
# 导入 MindSpore
import mindspore
# cell 同时输出多行
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np
from mindspore import Tensor
from mindspore import dtype
# 用数组创建张量
x = Tensor(np.array([[1, 2], [3, 4]]), dtype.int32)
x

Tensor(shape=[2, 2], dtype=Int32, value=
[[1, 2],
 [3, 4]])

用数值创建 Tensor

In [2]:
# 用数值创建张量
y = Tensor(1.0, dtype.int32)
z = Tensor(2, dtype.int32)
y
z

Tensor(shape=[], dtype=Int32, value= 1)

Tensor(shape=[], dtype=Int32, value= 2)

用 Bool 值创建 Tensor

In [3]:
# 用 Bool 值创建张量
m = Tensor(True, dtype.bool_)
m

Tensor(shape=[], dtype=Bool, value= True)

用 tuple 创建 Tensor

In [4]:
# 用 tuple 创建张量
n = Tensor((1, 2, 3), dtype.int16)
n

Tensor(shape=[3], dtype=Int16, value= [1, 2, 3])

用 list 创建 Tensor

In [5]:
# 用 list 创建张量
p = Tensor([4.0, 5.0, 6.0], dtype.float64)
p

Tensor(shape=[3], dtype=Float64, value= [ 4.00000000e+00,  5.00000000e+00,  6.00000000e+00])

继承另一个张量的属性，创建新的张量

In [6]:
from mindspore import ops

oneslike = ops.OnesLike()
x = Tensor(np.array([[0, 1], [2, 1]]).astype(np.float32))
output = oneslike(x)
output

Tensor(shape=[2, 2], dtype=Float32, value=
[[ 1.00000000e+00,  1.00000000e+00],
 [ 1.00000000e+00,  1.00000000e+00]])

输出恒定值 Tensor

In [7]:
from mindspore.ops import operations as ops

shape = (2, 2)
ones = ops.Ones()
output = ones(shape, dtype.float32)
print(output)

zeros = ops.Zeros()
output = zeros(shape, dtype.float32)
print(output)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


张量的属性包括形状（shape）、数据类型（dtype）

In [8]:
x = Tensor(np.array([[1, 2], [3, 4]]), dtype.int32)

x.shape # 形状
x.dtype # 数据类型
x.ndim # 维度
x.size # 大小

(2, 2)

mindspore.int32

2

4

Tensor的方法

In [9]:
y = Tensor(np.array([[True, True], [False, False]]), dtype.bool_)

# 将 Tensor 数据类型转化成 NumPy
y_array = y.asnumpy()

y
y_array

Tensor(shape=[2, 2], dtype=Bool, value=
[[ True,  True],
 [False, False]])

array([[ True,  True],
       [False, False]])

索引和切片

In [11]:
tensor = Tensor(np.array([[0, 1], [2, 3]]).astype(np.float32))
print("First row: {}".format(tensor[0]))
print("First column: {}".format(tensor[:, 0]))
print("Last column: {}".format(tensor[:, -1]))

First row: [0. 1.]
First column: [0. 2.]
Last column: [1. 3.]


Tensor 拼接

In [12]:
data1 = Tensor(np.array([[0,1], [2,3]]).astype(np.float32))
data2 = Tensor(np.array([[4,5],[6,7]]).astype(np.float32))
op = ops.Stack()
output = op([data1, data2])
print(output)

[[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]
